functionsDirectory = "/home/arnold/webapp/webapp/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/arnold/webapp/webapp/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/home/arnold/webapp/webapp/netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions.treasury-auto-payout]
  schedule = "*/1 * * * *"

  [functions."*"]

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]